<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiLocale\Event\LocaleListener'       => __DIR__ . '/src/ZucchiLocale/Event/LocaleListener.php',
    'ZucchiLocale\Controller\AdminController' => __DIR__ . '/src/ZucchiLocale/Controller/AdminController.php',
    'ZucchiLocale\Handler\HandlerInterface'   => __DIR__ . '/src/ZucchiLocale/Handler/HandlerInterface.php',
    'ZucchiLocale\Handler\Cookie'             => __DIR__ . '/src/ZucchiLocale/Handler/Cookie.php',
    'ZucchiLocale\Handler\Route'              => __DIR__ . '/src/ZucchiLocale/Handler/Route.php',
    'ZucchiLocale\Handler\Header'             => __DIR__ . '/src/ZucchiLocale/Handler/Header.php',
    'ZucchiLocale\Handler\Host'               => __DIR__ . '/src/ZucchiLocale/Handler/Host.php',
    'ZucchiLocale\Handler\AbstractHandler'    => __DIR__ . '/src/ZucchiLocale/Handler/AbstractHandler.php',
    'ZucchiLocale\Handler\Query'              => __DIR__ . '/src/ZucchiLocale/Handler/Query.php',
    'ZucchiLocale\Handler\Session'            => __DIR__ . '/src/ZucchiLocale/Handler/Session.php',
    'ZucchiLocale\Form\Locale'                => __DIR__ . '/src/ZucchiLocale/Form/Locale.php',
    'ZucchiLocale\View\Helper\Tranzlate'      => __DIR__ . '/src/ZucchiLocale/View/Helper/Tranzlate.php',
);