<?php
/**
 * ZucchiLocale (http://zucchi.co.uk/)
 *
 * @link      http://github.com/zucchi/ZucchiLocale for the canonical source repository
 * @copyright Copyright (c) 2005-2012 Zucchi Limited (http://zucchi.co.uk)
 * @license   http://zucchi.co.uk/legals/bsd-license New BSD License
 */
namespace ZucchiLocale\Controller;

use Zend\View\Model\ViewModel;

use ZucchiAdmin\Controller\AbstractAdminController;
use ZucchiAdmin\Crud\ControllerTrait as CrudControllerTrait;
use Zucchi\Debug\Debug;
use ZucchiLocale\Form\Locale AS LocaleForm;

/**
 * Controller to allow manipulation of locale settings
 * 
 * @author Matt Cockayne <matt@zucchi.co.uk>
 * @package ZucchiLocale
 * @subpackage Controller
 * @category Admin
 */
class AdminController extends AbstractAdminController 
{
    /**
     * Actino to control settings
     * 
     * @return \Zend\View\Model\ViewModel
     */
    public function settingsAction()
    {
        $path = getcwd() . '/config/autoload/zucchilocale.local.php';
        
        if (file_exists($path)) {
            !$data = include $path;
        } else {
            $data = array('ZucchiLocale' => array('locale' => array()));
        }
        
        $form = new LocaleForm();
        
        if ($this->request->isPost()) {
             $form->setData($this->request->getPost());
             if ($form->isValid()) {
                 $data['ZucchiLocale'] = $form->getData();
                 file_put_contents($path, 
                     '<?php // autogenerated file by ZucchiLocale ' . PHP_EOL . 
                     'return ' . var_export($data, true) . ';'
                 );
                 $this->messenger()->addMessage('New settings saved', 'success', 'Saved', true);
             } else {
                 $this->messenger()->addMessage($form->getMessages(), 'error', 'Unable to save', true);
             }
        } else {
            $form->setData($data['ZucchiLocale']);
        }
        
        
        
        
        return $this->loadView('zucchi-locale/admin/settings',array(
            'form' => $form,
        ));
    }
}
